for when running manually, clean up processes when script is killed

diff --git a/test/api/python/test.sh.in b/test/api/python/test.sh.in
--- a/test/api/python/test.sh.in
+++ b/test/api/python/test.sh.in
@@ -24,11 +24,23 @@ ZMQ_LIB_DIR=@ZEROMQ_LIBDIR@
 WITHOUT_PYTHON=@WITHOUT_PYTHON@
 PYTHON=@PYTHON@
 
+# clean up everything we started
+kill_all()
+{
+  echo killing pid = $SDPID
+  kill -TERM $SDPID
+}
+
 if test $WITHOUT_PYTHON = no;
 then
 
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    pushd $SCRIPT_DIR
+
+   # trap keyboard interrupt (control-c) and TERM signal
+   trap kill_all SIGINT
+   trap kill_all SIGUSR1
+   trap kill_all SIGTERM
 
    export PATH=$PATH:../../../src/components/cpp/bin
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ZMQ_LIB_DIR:../../../src/api/cpp:../../../src/keyvalue_parser:$ZMQ_LIB_DIR:$PROTOBUF_LIB_DIR
